import type { Metadata } from 'next'
import { Shantell_Sans } from 'next/font/google'
import './globals.css'
import { QueryProvider, StoreProvider } from '@/components/providers'

const shantellSans = Shantell_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={shantellSans.className}>
        <StoreProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
